#!/bin/bash
#

## fls -> file ls


#TODO: Providenciar a verificação de vários tipos de arquivos
#      ao mesmo tempo. $1$2 $1$3 $1$4 e assim por diante.
#      $1 indica o diretório. Os demais aos arquivos.

## É usado IFS para ser ignorado espaço e tabulação, e considerar
#  apenas o 'linefeed' como separador.
IFSb=IFS
IFS="
"
FILES=`eval ls '$@' 2>&1`
for FILE in $FILES; do
    if [ -f $FILE ]; then
        # O retorno será apenas o arquivo,
        # sem a indicação do diretório.
        echo ${FILE##*'/'}
    fi
done
IFS=IFSb
