#!/bin/bash
#

# sbackslash -> Back slash

## Opção --help
if [ "$1" = "-h" ] || [ "--help" ] || [ "$1" = "" ] || [ "$1" = "-r"] || [ "$1" = "--read"]; then
    echo ""
    echo -e "\033[32;1mSinopse:\033[m"
    echo "ef -h | --help | -r | --read | string"
    echo ""
    echo -e "\033[32;1mDescrição:\033[m"
    echo -e '\t\033[1m-h\033[m ou \033[1m--help\033[m : esta ajuda.'
    echo ""
    echo -e "\t    \033[1mstrcons\033[m é uma extensão do comando \033[1mschsub\033[m."
    echo -e "\t    Inclui uma contra barra (\033[1m \\ \033[m) na posição"
    echo -e "\timediatamente anterior ao espaço. \033[1m\" \"\033[m."

    echo -e "\033[32;1mExemplo:\033[m"
    echo -e "\tsbs \"string\""
    echo -e "\tsbs \"\$string\""
    echo -e "\tsbs \"\$path\""
    echo ""
    exit
fi

#TODO:  Providenciar a verificação a inclusão da 
#       contra-barra para todos dos caracteres extendidos.

echo `schsub "$1" " " "\ "`

