#!/bin/bash
#

## scuttail -> scttl -> string cut tail

ARG=$1
[ "$3" = "" ] && let count=1 || count=$3
case $count in
    [0-9] | [0-9][0-9] )
        let i=0
        while (( $i < $count )) ; do
            ARG=${ARG%$2*}
            [ "$ARG" = "" ] && break
            ((i++))
        done
        ;;
esac
echo $ARG
