#!/bin/bash
#

appName=${0##*'/'}

sblist="sb.lst"
readme="readme.txt"
bashprofile=$HOME"/.bash_profile"
installdir="bashscripts"
binpath="/usr/local/bashscripts/"               # Local de instalação
binpath2="~/.usr/local/bashscripts/"            # Local de instalação
infopath="info/"
#documents="$HOME/.usr/local/bashscripts/"
# documents="/usr/local/bashscripts/"
if [[ ! -d $documents ]]; then
    documents="./info/"
fi

#binpath="$HOME/.usr/bin/"
# binpath="/usr/bin/"
# SBSUPPORT_param1="parametro1"

TRUE=1
FALSE=0

bold="\033[1m"
normal="\033[m"

printsblist() {

    LINES=`cat $1 2>&1`
    for LINE in $LINES; do
        [ $LINE == ${LINE##*'['} ] && [ $LINE == ${LINE##*'#'} ] && {
            RET="$RET $LINE"
        }
    done

    echo $RET
}

__cutdoublebars () {

    local path
    local l=""

    # path=${1//'::'/':'} <- Does not work

    for ((i=0;i<=${#1};i++)); do
        b=${1:(($i)):((1))}
        [ "$b" = "$l" ] && [ "$b" = "/" ] || path=$path$b
        l=$b
    done
    echo "$path"
}

concatpath () {

    for p in $@; do
        path=$path/$p
    done
    [ -d $path ] && path=$path'/'
    echo $(__cutdoublebars "$path")
}

isScript() {

    local txt="#!/bin/bash"
    LINES=`cat $1`
    for LINE in $LINES; do
        [ $LINE != "${LINE##*$txt}" ] && { echo 1; exit 1; }
    done
    echo 0
    exit 0
}

isSBlist() {

    local txt="#?>sblist"
    LINES=`cat $1`
    for LINE in $LINES; do
        [ $LINE != "${LINE##*$txt}" ] && { echo 1; exit 1; }
    done
    echo 0
    exit 0
}

get_path () {

    local IFS="
"
    if [ -e $bashprofile ]; then
        # Captura o comteúdo do PATH
        LINES=`cat $bashprofile 2>&1`
        for LINE in $LINES; do
            # Retorna 0 se $path estiver contido em LINE.
            [ $LINE != ${LINE#'PATH='} ] && { break; }
        done
        echo $LINE
    else
        echo ""
    fi
}

set_path () {

    local IFS="
"
    if [[ -e $bashprofile ]]; then

        # Obtem a data que será incluido no texto, e na extensão do arquivo.
        # corrdata=`date +%d" de "%B" de "%Y" as "%H:%M:%S`
        bashProfileOld=$bashprofile"__"$(date +%Y-%m-%d"_at_"%H:%M:%S)

        # Renomeia '.bash_profile' para $bashProfileOld
        `mv $bashprofile $bashProfileOld`

        # Cria novo .bash_profile
        `touch $bashprofile`

        # Cria o conteúdo do novo .bash_profile com o novo PATH.
        LINES=`cat $bashProfileOld 2>&1`
        for LINE in $LINES; do
            # Retorna 0 se $path estiver contido em LINE.
            if [ "$LINE" != ${LINE#'PATH='} ]; then
                echo "PATH=$1" >> $bashprofile
            else
                echo "$LINE" >> $bashprofile
            fi
        done
    else
        echo "PATH=$1" > $bashprofile
    fi
}

prepers_path() {

    PL=$1
    PL=${PL#'PATH='}
    PL=${PL//'$PATH'/''}
    PL=${PL//'::'/':'}    # Troca dois pontos duplicados por apena um.
    PL=${PL%':'}          # Tira dois pontos do fim da linha.
    PL=${PL#':'}          # Tira dois pontos do início da linha.
    [ "$PL" = "" ] && PL='$PATH' || PL='$PATH:'"$PL"
    echo $PL
}

include_path() {

## Atual PATH
# /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/CrossPack-AVR/bin

    # include não pode ser vazio
    local include=${1%/}
    local exist="FALSE"
    local IFS=":"

    include=$(__cutdoublebars "$include")
    #  Verifica o PATH do sistema.
    PLINE=$PATH
    for PITEM in $PLINE; do
        [ "$include" = "$PITEM" ] && { exist="TRUE"; break; }
    done

    # Verifica o PATH em .bash_profile
    PLINE=$(get_path)
    for PITEM in $PLINE; do
        [ "$include" = "$PITEM" ] && { exist="TRUE"; break; }
    done

    if [ "$exist" = "FALSE" ]; then
        set_path "$(prepers_path $PLINE):$include"
    fi
}

exclude_path() {

	local exclude=${1%/}
    local exist=""
    local IFS=":"

    exclude=$(__cutdoublebars "$exclude")
    # Verifica o PATH em .bash_profile
    PLINE=$(get_path)
    for PITEM in $PLINE; do
        [ "$exclude" = "$PITEM" ] && { exist="TRUE"; break; }
    done
    IFS=$IFSb

    if [ "$exist" = "TRUE" ]; then
        PLINE=${PLINE//"$exclude"/''}     # Exclui o caminho indicado.
        set_path $(prepers_path $PLINE)
    fi
}

showInfo() {

    if [ -e $documents$1".info" ]; then
        source $documents$1".info" $1
    fi    
}

showTextFile() {

    local IFS="
"
    if [[ -f $1 ]]; then
        LINES=`cat $1 2>&1`
        for LINE in $LINES; do
            echo $LINE
        done
    fi
}

showReadMe() {

    if [ -f $documents$readme ]; then
        echo ""
        echo "====== Conteúdo do arquivo 'readme' ======"
        echo ""
        showTextFile $documents$readme 
        echo ""
        echo "==========================================="
        echo ""
        return 1
    else
        echo "Arquivo 'readme.txt' não encontrado!"
        echo ""
        echo `pwd`
        echo $documents$readme
        return 0
    fi
}

tr_lower () {
    echo $1 | tr "[:upper:]" "[:lower:]"
}

case $(tr_lower "$1") in
    --source | "" ) [ $0 = $appName ] && exit 0 || return 0 ;;
    --concatpath )  shift; concatpath $@ ;;
    --includepath ) include_path "$2";;
    --excludepath ) exclude_path "$2";;
	--pathdocs )    echo $documents;;
	--list )        echo $sblist;;
	--pathlist )    echo $documents$sblist;;
	--pathreadme )  echo $documents$readme;;
	--pathbin )     echo $binpath;;
	--env )         echo $0 $appName;;
    --readme )      showReadMe;;
    --print )       showTextFile "$2";;
    --help )        showInfo $appName;;
    --test )        echo 1;;
    * )             echo "- Parâmentro não reconhecido!";; # showInfo $1;;
esac

# unset prnt
# unset setupPath
# unset exclude_path

