#!/bin/bash
#

## schsub -> String Change Sub String

if [ "$1" = "--help" ] || [ "$1" = "--readme" ]; then
	source ./sbsupport "$1"
	exit
fi

[ "$1" = "" ] || [ $'2' = "" ] && exit 128
ARG="$1"
## Para compatibilidade com 'dash' do Raspberry
let i=${#1}-1
let t=${#2}
while (( $i >= 0 )) ; do
    if [ "${ARG:$i:t}" = "$2" ]; then
        ARG=${ARG:0:$i}$3${ARG:$((i+t))}
    fi
    ((i--))
done
echo "$ARG"
