#!/bin/bash
#

## scutup -> String Cut Up

if [ "$1" = "--help" ] || [ "$1" = "--readme" ]; then
    if [ -e sbsupport ]; then
        source sbsupport "$1"
    else
        echo "- Arquivo de ajuda não encontrado!"
    fi
    exit
fi

ARG=$1
[ "$3" = "" ] && let count=1 || count=$3
case $count in
    [0-9] | [0-9][0-9] )
        let i=0
        while (( $i < $count )) ; do
            rsl=${ARG%$2*}
            ((i++))
            [ "$ARG" = "$rsl" ] && ARG="$1" && break || ARG="$rsl"
            [ "$ARG" = "" ] && break
        done
        [ $((count-i)) -le 0 ] && ARG=${1#$ARG$2} || ARG="$1"
        ;;
esac
echo $ARG
