#!/bin/bash
#

## ssube

if [ "$1" = "--help" ] || [ "$1" = "--readme" ]; then
	source sbsupport "$1" 2>&1
	exit $?
fi

[ "$1" = "" ] || [ "$2" = "" ] && exit 128
ARG="$1"
## Para compatibilidade com 'dash' do Raspberry
let t2=${#2}
let t1=${#1}-$t2
let i=0
while (( $i <= $t1 )) ; do
    if [ "${ARG:$i:t2}" = "$2" ]; then
        echo 1
        exit
    fi
    ((i++))
done
echo 0

